field.formatter.settings.mirador:
  type: mapping
  label: 'Entity reference field formatter settings.'
  mapping:
    mirador_node_style:
      type: string
      label: 'Node Style'
    mirador_settings:
      type: string
      label: 'Mirador Settings'
